project:
  type: website
  output-dir: out
  preview:
    port: 4300
    browser: false

website:
  site-url: "https://kspviswa.github.io/slicenet-demo"
  favicon: "slicenet-1-tr-logo.png"
  title: "Slicenet Demo & Dashboard"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Features"
        contents:
          - preso.qmd
      - section: "Dashboard"
        contents:
          - demo.qmd

format:
  html:
    theme: sketchy
  revealjs:
    theme: sketchy
  dashboard:
    theme: sketchy
